form-flow:
  applications-disabled: ${DISABLE_APPLICATIONS:-"false"}
  laterdoc-delay-disabled: ${DISABLE_LATERDOC_DELAY:-"false"}
  inputs: 'org.homeschoolpebt.app.inputs.'
  uploads:
    accepted-file-types: '.jpeg,.jpg,.png,.pdf,.bmp,.gif,.doc,.docx,.odt,.ods,.odp'
    thumbnail-width: '64'
    thumbnail-height: '60'
    # 20 files maximum
    max-files: '20'
    # 20 MB file size limit
    # If this is not set then the server values below for servlet max-file-size and tomcat max POST size will not be set
    # which will cause the server to use the default values of 1MB preventing uploads larger than that.
    max-file-size: '20'
  aws:
    region: 'us-west-1'
    s3_bucket_name: ${AWS_BUCKET_NAME:-""}
    access_key: ${AWS_ACCESS_KEY:-""}
    secret_key: ${AWS_SECRET_KEY:-""}
  address-validation:
    disabled: false
    smarty:
      auth-id: ${SMARTY_AUTH_ID:-""}
      auth-token: ${SMARTY_AUTH_TOKEN:-""}
      license: us-core-cloud
  pdf:
    path: 'src/main/resources/pdfs/'
    map-file: pdf-map.yaml
  email-client:
    mailgun:
      sender-email: noreply@${MAILGUN_DOMAIN:-""}
      key: ${MAILGUN_API_KEY:-""}
      domain: ${MAILGUN_DOMAIN:-""}
spring:
  profiles:
    group:
      production:
        - production
        - form-flow-library
      test:
        - test
        - form-flow-library
      dev:
        - dev
        - form-flow-library
      demo:
        - demo
        - form-flow-library
  session:
    store-type: jdbc
    timeout: 72h
    jdbc:
      initialize-schema: always
  thymeleaf:
    cache: false
    template-resolver-order: 0
    check-template-location: true
  # TODO: move caching 0 to a dev only context?
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  shell:
    interactive.enabled: false
    history:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/starter-app
    username: starter-app
    password:
  flyway:
    out-of-order: true
  servlet:
    multipart:
      max-file-size: ${form-flow.uploads.max-file-size}MB
      max-request-size: ${form-flow.uploads.max-file-size}MB
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  pattern:
    console:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.apache.commons.beanutils: INFO
server:
  tomcat:
    max-http-form-post-size: ${form-flow.uploads.max-file-size}MB
  error:
    whitelabel:
      enabled: false
sftp:
  username: ${SFTP_USERNAME:-""}
  password: ${SFTP_PASSWORD:-""}
  upload-url: ${SFTP_UPLOAD_URL:-""}
sentry:
  traces-sample-rate: 0.3
  environment: production
  exception-resolver-order: -2147483647 # send to sentry exceptions handled by @ExceptionHandler's
twilio:
  account.sid: ${TWILIO_ACCOUNT_SID:-""}
  auth.token: ${TWILIO_AUTH_TOKEN:-""}
  messaging.service.sid: ${TWILIO_MESSAGING_SERVICE_SID:-""}
mixpanel:
  token: ${MIXPANEL_TOKEN:-""}
