name: pebt
flow:
  howThisWorks:
    nextScreens:
      - name: eligibility

  # Step 1 of 6: Pre-Screen
  eligibility:
    nextScreens:
      - name: preScreenMoreThanOneStudent
  preScreenMoreThanOneStudent:
    nextScreens:
      - name: preScreenEnrolledInVirtualSchool
        condition: PreScreenHasMoreThanOneStudent
      - name: preScreenApplyingForSelf
  preScreenApplyingForSelf:
    nextScreens:
      - name: preScreenEnrolledInVirtualSchool
  preScreenEnrolledInVirtualSchool:
    nextScreens:
      - name: preScreenIneligible
        condition: PreScreenNotEnrolledInVirtualSchool
      - name: preScreenUnenrolled
  preScreenUnenrolled:
    nextScreens:
      - name: preScreenIneligible
        condition: PreScreenNotUnenrolledFromVirtualSchool
      - name: preScreenUnenrolledSchoolName
  preScreenUnenrolledSchoolName:
    nextScreens:
      - name: eligibilityLikely
  preScreenIneligible:
    nextScreens: []
  eligibilityLikely:
    nextScreens:
      - name: studentsSignpost

  # Step 2 of 6: Student Information
  studentsSignpost:
    nextScreens:
      - name: studentsAdd
  studentsAdd:
    subflow: students
    onPostAction: UpdateStudentBirthday
    nextScreens:
      - name: studentsDesignations
  studentsDesignations:
    subflow: students
    nextScreens:
      - name: studentsSchoolYear
  studentsSchoolYear:
    subflow: students
    nextScreens:
      - name: studentsWouldAttendSchoolName
        condition: PreScreenHasOnlyOneStudent
      - name: studentsUnenrolledSchoolName
  studentsUnenrolledSchoolName:
    subflow: students
    nextScreens:
      - name: studentsWouldAttendSchoolName
  studentsWouldAttendSchoolName:
    subflow: students
    nextScreens:
      - name: studentsSummary
  studentsSummary:
    nextScreens:
      - name: applicantIsInHousehold
        condition: PreScreenNotApplyingForSelf
      - name: gettingToKnowYou
  studentsDeleteConfirmation:
    nextScreens: null
  applicantIsInHousehold:
    nextScreens:
      - name: gettingToKnowYou


  # Step 3 of 6: Basic Info ("Getting to know you")
  gettingToKnowYou:
    nextScreens:
      - name: personalInfo
  personalInfo:
    nextScreens:
      - name: homeAddress
  homeAddress:
    nextScreens:
      - name: contactInfo
        condition: HomeAddressValidationIsOff
      - name: pickHomeAddress
        condition: SmartySuggestionFound
      - name: verifyHomeAddress
        condition: SmartySuggestionNotFound
  pickHomeAddress:
    nextScreens:
      - name: contactInfo
  verifyHomeAddress:
    nextScreens:
      - name: contactInfo
  contactInfo:
    nextScreens:
      - name: confirmBlankEmail
        condition: HasBlankEmail
      - name: reviewPersonalInfo
  confirmBlankEmail:
    nextScreens:
      - name: reviewPersonalInfo
  reviewPersonalInfo:
    nextScreens:
      - name: housemates

  # Step 4 of 6: Household builder ("Household Details")
  housemates:
    nextScreens:
      - name: signpostHouseholdDetails
        condition: HasHousehold
      - name: signpostIncome
  signpostHouseholdDetails:
    nextScreens:
      - name: housemateInfo
  housemateInfo:
    subflow: household
    nextScreens:
      - name: householdList
  householdList:
    nextScreens:
      - name: householdReceivesBenefits
  householdReceivesBenefits:
    nextScreens:
      - name: signpostIncome
  householdDeleteConfirmation:
    nextScreens: null

  # Step 5 of 6: Income
  signpostIncome:
    nextScreens:
      - name: hasIncome
  hasIncome:
    nextScreens:
      - name: incomeAddJob
        condition: HasIncome
      - name: economicHardship
  incomeAddJob:
    nextScreens:
      - name: incomeChooseHouseholdMember
  incomeChooseHouseholdMember:
    subflow: income
    nextScreens:
      - name: incomeJobName
  incomeJobName:
    subflow: income
    nextScreens:
      - name: incomeSelfEmployed
  incomeSelfEmployed:
    subflow: income
    nextScreens:
      - name: incomeSelfEmployedGrossMonthly
        condition: IsJobSelfEmployed
      - name: incomeIsJobHourly
  incomeIsJobHourly:
    subflow: income
    nextScreens:
      - name: incomeHourlyWageCalculator
        condition: IsJobHourly
      - name: incomeRegularPayCalculator
  incomeHourlyWageCalculator:
    subflow: income
    nextScreens:
      - name: incomeWillBeLessYearly
        condition: IsJobPaidYearly
      - name: incomeWillBeLessMonthly
  incomeGrossMonthlyIndividual:
    subflow: income
    nextScreens:
      - name: incomeWillBeLessYearly
        condition: IsJobPaidYearly
      - name: incomeWillBeLessMonthly
  incomeRegularPayCalculator:
    subflow: income
    nextScreens:
      - name: incomeWillBeLessYearly
        condition: IsJobPaidYearly
      - name: incomeWillBeLessMonthly
  incomeWillBeLessYearly:
    subflow: income
    nextScreens:
      - name: incomeReview
  incomeWillBeLessMonthly:
    subflow: income
    nextScreens:
      - name: incomeReview
  incomeSelfEmployedGrossMonthly:
    subflow: income
    nextScreens:
      - name: incomeSelfEmployedOperatingExpenses
  incomeSelfEmployedOperatingExpenses:
    subflow: income
    nextScreens:
      - name: incomeSelfEmployedWillBeLess
  incomeSelfEmployedWillBeLess:
    subflow: income
    nextScreens:
      - name: incomeReview
  incomeReview:
    nextScreens:
      - name: incomeEarnedIncomeComplete
  incomeEarnedIncomeComplete:
    nextScreens:
      - name: incomeUnearnedRetirementTypes
  incomeUnearnedRetirementTypes:
    nextScreens:
      - name: incomeUnearnedTypes
  incomeUnearnedTypes:
    nextScreens:
      - name: incomeUnearnedAmounts
  incomeUnearnedAmounts:
    nextScreens:
      - name: incomeComplete
  incomeComplete:
    nextScreens:
      - name: economicHardship
  economicHardship:
    nextScreens:
      - name: addingDocuments

  # Step 6 of 6: Adding documents
  addingDocuments:
    nextScreens:
      - name: howToAddDocuments
  howToAddDocuments:
    nextScreens:
      - name: documentRecommendations
  documentRecommendations:
    nextScreens:
      - name: uploadIdentityDocuments
  documentOffboarding:
    nextScreens:
      - name: submitting
  uploadIdentityDocuments:
    nextScreens:
      - name: uploadEnrollmentDocuments
  uploadEnrollmentDocuments:
    nextScreens:
      - name: uploadIncomeDocuments
  uploadIncomeDocuments:
    nextScreens:
      - name: docSubmitConfirmation
  docSubmitConfirmation:
    nextScreens:
      - name: submitting

  # Step 7: Sign + Submit!
  submitting:
    nextScreens:
      - name: legalStuff
  legalStuff:
    nextScreens:
      - name: signName
  signName:
    afterSaveAction: HandleApplicationSigned
    nextScreens:
      - name: nextSteps
  nextSteps:
    nextScreens:
      - name: success
  success:
    nextScreens: null

subflows:
  students:
    entryScreen: studentsSignpost
    iterationStartScreen: studentsAdd
    reviewScreen: studentsSummary
    deleteConfirmationScreen: studentsDeleteConfirmation
  household:
    entryScreen: housemates
    iterationStartScreen: housemateInfo
    reviewScreen: householdList
    deleteConfirmationScreen: householdDeleteConfirmation
  income:
    entryScreen: hasIncome
    iterationStartScreen: incomeChooseHouseholdMember
    reviewScreen: incomeReview
    deleteConfirmationScreen: incomeDeleteConfirmation
---
name: docUpload
flow:
  uploadDocuments:
    nextScreens:
      - name: success
  success:
    nextScreens: null
