name: pebt
flow:
  howThisWorks:
    nextScreens:
      - name: eligibility

  # Step 1 of 6: Pre-Screen
  eligibility:
    nextScreens:
      - name: preScreenMoreThanOneStudent
  preScreenMoreThanOneStudent:
    nextScreens:
      - name: preScreenEnrolledInVirtualSchool
        condition: PreScreenHasMoreThanOneStudent
      - name: preScreenApplyingForSelf
  preScreenApplyingForSelf:
    nextScreens:
      - name: preScreenEnrolledInVirtualSchool
  preScreenEnrolledInVirtualSchool:
    nextScreens:
      - name: preScreenIneligible
        condition: PreScreenNotEnrolledInVirtualSchool
      - name: preScreenUnenrolled
  preScreenUnenrolled:
    nextScreens:
      - name: preScreenIneligible
        condition: PreScreenNotUnenrolledFromVirtualSchool
      - name: preScreenUnenrolledSchoolName
  preScreenUnenrolledSchoolName:
    nextScreens:
      - name: eligibilityLikely
  preScreenIneligible:
    nextScreens: []
  eligibilityLikely:
    nextScreens:
      - name: studentsAdd

  # Step 2 of 6: Student Information
  # TODO: Add studentInfoSignpost page here
  studentsAdd:
    subflow: students
    nextScreens:
      - name: languagePreference

  # Step 3 of 6: Basic Info ("Getting to know you")
  languagePreference:
    nextScreens:
      - name: gettingToKnowYou
  gettingToKnowYou:
    nextScreens:
      - name: personalInfo
  personalInfo:
    nextScreens:
      - name: homeAddress
  homeAddress:
    nextScreens:
      - name: contactInfo
        condition: HomeAddressValidationIsOff
      - name: pickHomeAddress
        condition: SmartySuggestionFound
      - name: verifyHomeAddress
        condition: SmartySuggestionNotFound
  pickHomeAddress:
    nextScreens:
      - name: contactInfo
  verifyHomeAddress:
    nextScreens:
      - name: contactInfo
  contactInfo:
    beforeSaveAction: SendConfirmationEmail
    nextScreens:
      - name: reviewPersonalInfo
  reviewPersonalInfo:
    nextScreens:
      - name: housemates
  housemates:
    nextScreens:
      - name: housemateInfo
        condition: HasHousehold
      - name: income
  housemateInfo:
    subflow: household
    nextScreens:
      - name: householdList
  householdList:
    nextScreens:
      - name: income
  householdDeleteConfirmation:
    nextScreens: null
  income:
    nextScreens:
      - name: householdMemberIncome
  householdMemberIncome:
    subflow: income
    nextScreens:
      - name: incomeTypes
  incomeTypes:
    subflow: income
    nextScreens:
      - name: incomeAmounts
  incomeAmounts:
    beforeSaveAction: UpdateIncomeAmountsBeforeSaving
    subflow: income
    nextScreens:
      - name: annualHouseholdIncome
  annualHouseholdIncome:
    nextScreens:
      - name: exceedsIncomeThreshold
        condition: ExceedsIncomeThreshold
      - name: incomeComplete
  incomeDeleteConfirmation:
    nextScreens: null
  reportedAnnualHouseholdIncome:
    nextScreens:
      - name: exceedsIncomeThreshold
        condition: ExceedsIncomeThreshold
      - name: incomeComplete
  incomeComplete:
    nextScreens:
      - name: economicHardship
  exceedsIncomeThreshold:
    nextScreens:
      - name: economicHardship
  economicHardship:
    nextScreens:
      - name: addingDocuments
  addingDocuments:
    nextScreens:
      - name: howToAddDocuments
  howToAddDocuments:
    nextScreens:
      - name: documentRecommendations
  documentRecommendations:
    nextScreens:
      - name: uploadUBIFlowDocuments
  documentOffboarding:
    nextScreens:
      - name: submitting
  uploadUBIFlowDocuments:
    nextScreens:
      - name: docSubmitConfirmation
  docSubmitConfirmation:
    nextScreens:
      - name: submitting
  submitting:
    nextScreens:
      - name: legalStuff
  legalStuff:
    nextScreens:
      - name: signName
  signName:
    nextScreens:
      - name: nextSteps
  nextSteps:
    nextScreens:
      - name: success
  success:
    nextScreens: null

subflows:
  students:
    entryScreen: eligibilityLikely # TODO: studentInfoSignpost
    iterationStartScreen: studentsAdd
    reviewScreen: languagePreference # TODO: build this page
    deleteConfirmationScreen: someOtherPage # TODO: bulid this page
  household:
    entryScreen: housemates
    iterationStartScreen: housemateInfo
    reviewScreen: householdList
    deleteConfirmationScreen: householdDeleteConfirmation
  income:
    entryScreen: income
    iterationStartScreen: householdMemberIncome
    reviewScreen: annualHouseholdIncome
    deleteConfirmationScreen: incomeDeleteConfirmation
---
name: docUpload
flow:
  uploadDocuments:
    nextScreens:
      - name: success
  success:
    nextScreens: null
