name: pebt
flow:
  howThisWorks:
    nextScreens:
      - name: eligibility

  # Step 1 of 6: Pre-Screen
  eligibility:
    nextScreens:
      - name: preScreenMoreThanOneStudent
  preScreenMoreThanOneStudent:
    nextScreens:
      - name: preScreenEnrolledInVirtualSchool
        condition: PreScreenHasMoreThanOneStudent
      - name: preScreenApplyingForSelf
  preScreenApplyingForSelf:
    nextScreens:
      - name: preScreenEnrolledInVirtualSchool
  preScreenEnrolledInVirtualSchool:
    nextScreens:
      - name: preScreenIneligible
        condition: PreScreenNotEnrolledInVirtualSchool
      - name: preScreenUnenrolled
  preScreenUnenrolled:
    nextScreens:
      - name: preScreenIneligible
        condition: PreScreenNotUnenrolledFromVirtualSchool
      - name: preScreenUnenrolledSchoolName
  preScreenUnenrolledSchoolName:
    nextScreens:
      - name: eligibilityLikely
  preScreenIneligible:
    nextScreens: []
  eligibilityLikely:
    nextScreens:
      - name: studentsSignpost

  # Step 2 of 6: Student Information
  studentsSignpost:
    nextScreens:
      - name: studentsAdd
  studentsAdd:
    subflow: students
    nextScreens:
      - name: studentsDesignations
  studentsDesignations:
    subflow: students
    nextScreens:
      - name: studentsWouldAttendSchoolName
        condition: PreScreenHasOnlyOneStudent
      - name: studentsUnenrolledSchoolName
  studentsUnenrolledSchoolName:
    subflow: students
    nextScreens:
      - name: studentsWouldAttendSchoolName
  studentsWouldAttendSchoolName:
    subflow: students
    nextScreens:
      - name: studentsSummary
  studentsSummary:
    nextScreens:
      - name: applicantIsInHousehold
        condition: PreScreenNotApplyingForSelf
      - name: languagePreference
  applicantIsInHousehold:
    nextScreens:
      - name: languagePreference


  # Step 3 of 6: Basic Info ("Getting to know you")
  languagePreference:
    nextScreens:
      - name: gettingToKnowYou
  gettingToKnowYou:
    nextScreens:
      - name: personalInfo
  personalInfo:
    nextScreens:
      - name: homeAddress
  homeAddress:
    nextScreens:
      - name: contactInfo
        condition: HomeAddressValidationIsOff
      - name: pickHomeAddress
        condition: SmartySuggestionFound
      - name: verifyHomeAddress
        condition: SmartySuggestionNotFound
  pickHomeAddress:
    nextScreens:
      - name: contactInfo
  verifyHomeAddress:
    nextScreens:
      - name: contactInfo
  contactInfo:
    beforeSaveAction: SendConfirmationEmail
    nextScreens:
      - name: reviewPersonalInfo
  reviewPersonalInfo:
    nextScreens:
      - name: housemates

  # Step 4 of 6: Household builder ("Household Details")
  housemates:
    nextScreens:
      - name: signpostHouseholdDetails
        condition: HasHousehold
      - name: signpostIncome
  signpostHouseholdDetails:
    nextScreens:
      - name: housemateInfo
  housemateInfo:
    subflow: household
    nextScreens:
      - name: householdList
  householdList:
    nextScreens:
      - name: householdReceivesBenefits
  householdReceivesBenefits:
    nextScreens:
      - name: signpostIncome
  householdDeleteConfirmation:
    nextScreens: null

  # Step 5 of 6: Income
  signpostIncome:
    nextScreens:
      - name: hasIncome
  hasIncome:
    nextScreens:
      - name: incomeChooseHouseholdMember
        condition: HasIncome
      - name: economicHardship
  incomeChooseHouseholdMember:
    subflow: income
    nextScreens:
      - name: incomeJobsCount
  incomeJobsCount:
    subflow: income
    nextScreens:
      - name: incomeWasSelfEmployed
  incomeWasSelfEmployed:
    subflow: income
    nextScreens:
      - name: incomeGrossMonthlyIndividual
      # TODO: Implement this condition when FFL supports conditional pages in sub-flows.
      # condition: HasMultipleJobsThatArentSelfEmployment
  incomeGrossMonthlyIndividual:
    subflow: income
    nextScreens:
      - name: incomeIsJobHourly
  incomeIsJobHourly:
    subflow: income
    nextScreens:
      - name: incomeHourlyWageCalculator
  incomeHourlyWageCalculator:
    subflow: income
    nextScreens:
      - name: incomeRegularPayCalculator
  incomeRegularPayCalculator:
    subflow: income
    nextScreens:
      - name: incomeReview

  incomeReview:
    nextScreens:
      - name: exceedsIncomeThreshold
        condition: ExceedsIncomeThreshold
      - name: incomeComplete

  incomeTypes:
    subflow: income
    nextScreens:
      - name: incomeAmounts
  incomeAmounts:
    beforeSaveAction: UpdateIncomeAmountsBeforeSaving
    subflow: income
    nextScreens:
      - name: annualHouseholdIncome
  incomeDeleteConfirmation:
    nextScreens: null
  reportedAnnualHouseholdIncome:
    nextScreens:
      - name: exceedsIncomeThreshold
        condition: ExceedsIncomeThreshold
      - name: incomeComplete
  incomeComplete:
    nextScreens:
      - name: economicHardship
  exceedsIncomeThreshold:
    nextScreens:
      - name: economicHardship
  economicHardship:
    nextScreens:
      - name: addingDocuments
  addingDocuments:
    nextScreens:
      - name: howToAddDocuments
  howToAddDocuments:
    nextScreens:
      - name: documentRecommendations
  documentRecommendations:
    nextScreens:
      - name: uploadUBIFlowDocuments
  documentOffboarding:
    nextScreens:
      - name: submitting
  uploadUBIFlowDocuments:
    nextScreens:
      - name: docSubmitConfirmation
  docSubmitConfirmation:
    nextScreens:
      - name: submitting
  submitting:
    nextScreens:
      - name: legalStuff
  legalStuff:
    nextScreens:
      - name: signName
  signName:
    nextScreens:
      - name: nextSteps
  nextSteps:
    nextScreens:
      - name: success
  success:
    nextScreens: null

subflows:
  students:
    entryScreen: studentsSignpost
    iterationStartScreen: studentsAdd
    reviewScreen: studentsSummary
    deleteConfirmationScreen: someOtherPage # TODO: bulid this page
  household:
    entryScreen: housemates
    iterationStartScreen: housemateInfo
    reviewScreen: householdList
    deleteConfirmationScreen: householdDeleteConfirmation
  income:
    entryScreen: hasIncome
    iterationStartScreen: incomeChooseHouseholdMember
    reviewScreen: annualHouseholdIncome
    deleteConfirmationScreen: incomeDeleteConfirmation
---
name: docUpload
flow:
  uploadDocuments:
    nextScreens:
      - name: success
  success:
    nextScreens: null
