name: Pull Transifex English

on: workflow_dispatch # Manually triggered for now

env:
  TX_API_TOKEN: ${{ secrets.TX_API_TOKEN }}

jobs:
  pull_transifex_english:
    runs-on: ubuntu-latest
    environment: transifex
    steps:
      - uses: actions/checkout@v3

      - name: Pull source file using transifex client
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TX_API_TOKEN }}
          args: 'pull --force --source'

      - name: Create pull request
        run: |
          if git diff --exit-code; then
            echo "No changes detected!"
          else
            git checkout -b update-english-from-transifex origin/main
            git add --all
            git commit -m "Update English translations from Transifex"
            git push origin update-english-from-transifex --force
            if gh pr list --state open --label transifex-auto | grep 'no pull requests match'; then
              gh pr create -B main --fill --label transifex-auto
            else
              echo "Pull request already exists. Not recreating!"
            fi
          fi
