name: Pull Transifex English

on: workflow_dispatch # Manually triggered for now

env:
  TX_API_TOKEN: ${{ secrets.TX_API_TOKEN }}

jobs:
  pull_transifex_english:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull source file using transifex client
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TX_API_TOKEN }}
          args: 'pull --force --source'

      - name: Check for git diff
        continue-on-error: true
        run: git diff --exit-code

      - name: Create pull request
        if: ${{ failure() }}
        run: |
          git checkout -b update-english-from-transifex
          git add --all
          git commit -m "Update English translations from Transifex"
          gh pr create -B main --fill
