name: Pull Transifex English

on:
  schedule:
    # Run on weekdays 8am - 5pm.
    # 8AM PT = 15:00 UTC (PDT) or 16:00 UTC (PST)
    # 5PM PT = 00:00 UTC (PDT) or 01:00 UTC (PST)
    - cron: '0 0-1,15-23 * * MON-FRI'

env:
  TX_API_TOKEN: ${{ secrets.TX_API_TOKEN }}

jobs:
  pull_transifex_english:
    runs-on: ubuntu-latest
    environment: transifex
    steps:
      - uses: actions/checkout@v3

      - name: Pull source file using transifex client
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TX_API_TOKEN }}
          args: 'pull --force --source'

      - name: Create pull request
        env:
          GIT_AUTHOR_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git config --global user.name "$GIT_AUTHOR_NAME"
          if git diff -U0 --exit-code; then
            echo "No changes detected!"
          else
            git checkout -b update-english-from-transifex origin/main
            git add --all
            git commit -m "Update English translations from Transifex"
            git push origin update-english-from-transifex --force
            gh pr create -B main --fill --label transifex-auto || true
          fi
