name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:

env:
  USERNAME: ${{ secrets.GPR_USER }}
  TOKEN: ${{ secrets.GPR_KEY }}
  MAILGUN_DOMAIN: example.com
  MAILGUN_API_KEY: key-1234

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: starter-app-test
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: starter-app-test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2.1.1
      - uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test with Gradle
        run: ./gradlew --no-watch-fs clean test --stacktrace --info
      - name: Announce failures on Slack
        if: ${{ failure() && github.ref == 'main' }}
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
