name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:

env:
  USERNAME: ${{ secrets.GPR_USER }}
  TOKEN: ${{ secrets.GPR_KEY }}
  MAILGUN_DOMAIN: example.com
  MAILGUN_API_KEY: key-1234

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: starter-app-test
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: starter-app-test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1.0.8
      - name: Set up JDK
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew clean test --stacktrace
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Announce failures on Slack
        if: failure()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties